CREATE TABLE 'posts' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT(50) DEFAULT NULL,
'content' TEXT DEFAULT NULL,
'id_users' INTEGER NOT NULL  DEFAULT NULL REFERENCES 'users' ('id'),
'id_forums' INTEGER NOT NULL  DEFAULT NULL REFERENCES 'forums' ('id'),
'timeCreated' TEXT DEFAULT NULL
);

CREATE TABLE 'users' (
'id' INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT(50) DEFAULT NULL,
'email' TEXT(50) DEFAULT NULL,
'pfp_url' TEXT DEFAULT NULL
);

CREATE TABLE 'forums' (
'id' INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT(50) DEFAULT NULL,
'description' TEXT DEFAULT NULL,
'token' TEXT(5) DEFAULT NULL
);